### ISSUE TITLE
module 'word2vec-google-news-300' has no attribute 'load_data'

### ISSUE THREAD

**Issue by jarviszhb** [chaitaliSaini/gensim-data#37]
I tried to use gensim.downloader to download 'word2vec-google-news-300', but my network isn't very reliable, so I downloaded word2vec-google-news-300.gz and init.py from github and put them into ~/gensim-data/word2vec-google-news-300/. But when I use api.load("word2vec-google-news-300")to load this model, I recieved error like this:

AttributeError: module 'word2vec-google-news-300' has no attribute 'load_data'
```python
import gensim.downloader as api
model = api.load("word2vec-google-news-300")
```

**Comment by piskvorky** [comment]
Post the full stack trace please.

Plus your versions of Python, gensim and OS.

**Comment by aniruddhakal** [comment]
what was the resolution?
I'm facing this same issue.

OS: Ubuntu 19.10
gensim version: 3.8.1

Stack Trace:
--------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
<ipython-input-4-f5399884feeb> in <module>
      1 import gensim.downloader as api
      2 
----> 3 api.load('glove-twitter-100')

/usr/local/lib/python3.7/dist-packages/gensim/downloader.py in load(name, return_path)
    500         sys.path.insert(0, BASE_DIR)
    501         module = __import__(name)
--> 502         return module.load_data()
    503 
    504 

AttributeError: module 'glove-twitter-100' has no attribute 'load_data'
```

**Comment by piskvorky** [comment]
I cannot replicate, on the same Ubuntu 19.10 and gensim 3.8.1.

Does your `~/gensim-data` directory look like this?

```bash
(tst) [radim@h3:~/gensim-data]$ ls -l
total 28
drwx------ 2 radim radim  4096 Mar 16 10:32 glove-twitter-100
-rw-r--r-- 1 radim radim 21626 Mar 16 10:34 information.json

(tst) [radim@h3:~/gensim-data]$ ls -l glove-twitter-100/
total 396432
-rw-r--r-- 1 radim radim       256 Mar 16 10:32 __init__.py
-rw-r--r-- 1 radim radim       604 Mar 16 10:32 __init__.pyc
-rw-r--r-- 1 radim radim 405932991 Mar 16 10:32 glove-twitter-100.gz
```

**Comment by aniruddhakal** [comment]
Hi @piskvorky 

I fixed the issue, I had to elevate the access permission for .gz archive.
Thanks for the clue.

![gensim_fix](https://user-images.githubusercontent.com/2071408/76774581-03879e00-679c-11ea-905c-f5a9307f473d.png)

**Comment by piskvorky** [comment]
That's weird, that shouldn't be necessary. My snippet also had just `-rw-r--r--`. I guess you're loading the file in Python under a different user, not `aniruddha`, right?

Either way, we should probably fail with a more useful error message if opening the file fails. The current error is too cryptic.

Can you open a PR for that @aniruddhakal? Thanks.

**Comment by aniruddhakal** [comment]
@piskvorky No, I'm loading python program using the same user account.

Are you suggesting that I make changes and raise PR?
I'll be happy to do that.

**Comment by piskvorky** [comment]
Well, step one is finding out what's wrong. The fact that changing permissions to `-rwxrwxrwx` helped is a strong clue, but I still don't know why that's needed on your system.

Can you look deeper into the actual error, check that happens exactly when you leave permissions at `-rw-r--r--`?

**Comment by aniruddhakal** [comment]
@piskvorky I tried reproducing issue, by both setting the permissions to original; deleting directory and re-downloading.
Issue isn't reproducing that way.

I should have checked contents of __init__.py
Only way I could reproduce issue was by renaming __init__.py file.

Bdw, I'm having issues while generating docs as stated in guidelines. I'll raise PR for some another purpose some other time.
I was just adding try, except block and re-raise ModuleNotFoundError with message "Error occurred while loading/accessing the module: " + name
Can you please do it this time.
Thanks!
